### ISSUE TITLE
Error using example

### ISSUE THREAD

**Issue by JosiahParry** [mikey-harper/ggmapstyles#2]
Running your example code:

```
basemap <- get_snazzymap("Southampton, UK", mapRef = "https://snazzymaps.com/style/83/muted-blue")
#> Warning: package 'bindrcpp' was built under R version 3.4.4
ggmap(basemap)
```

Results in the following error:

```
Error in (function (..., row.names = NULL, check.rows = FALSE, check.names = TRUE,  : 
  arguments imply differing number of rows: 1, 0
```

The package seems cool, just can't get it to work!

**Comment by dr-harper** [comment]
I am unable to replicate your error. Have you got the latest version of ggmap installed and have a google maps API key? Since mid-2018, google maps requires a key for all API requests.

```r
devtools::install_github("dr-harper/ggmapstyles")
devtools::install_github("dkahle/ggmap")

library(ggmapstyles)
library(ggmap)

# get a key from google maps here: https://cloud.google.com/maps-platform/
register_google("")

basemap <- get_snazzymap("Southampton, UK", mapRef = "https://snazzymaps.com/style/83/muted-blue")
#> Warning: package 'bindrcpp' was built under R version 3.4.4
ggmap(basemap)
```

![image](https://user-images.githubusercontent.com/20046224/52241551-f0817980-28cb-11e9-9134-c92df7556823.png)

Check out the ggmap repository for instructions on how to get a key, and let me know if you have any further problems:https://github.com/dkahle/ggmap

**Comment by dr-harper** [comment]
Please let me know if this issue is still a problem, otherwise I will close the issue.
